name: aplikasi_monitoring
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  fl_chart: ^1.1.1
  mqtt_client: ^10.11.1
  http: ^1.5.0
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  font_awesome_flutter: ^10.10.0
  fluttertoast: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

