// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtkPDjwxSPfVDsjT4eDKF1wdjxl9EtRoI',
    appId: '1:229806959659:web:33236f97bddb5ff8d54e6e',
    messagingSenderId: '229806959659',
    projectId: 'monitoring-650f6',
    authDomain: 'monitoring-650f6.firebaseapp.com',
    storageBucket: 'monitoring-650f6.firebasestorage.app',
    measurementId: 'G-7J0VTPJRWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJcMJPQPVattuiLEidrf8bA-fBSr1fBI',
    appId: '1:229806959659:android:32a679b620c1429dd54e6e',
    messagingSenderId: '229806959659',
    projectId: 'monitoring-650f6',
    storageBucket: 'monitoring-650f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy_xiGpp6VEGHRoaLjGlFJdpIFrmOB2qU',
    appId: '1:229806959659:ios:84aa7625adae8fa0d54e6e',
    messagingSenderId: '229806959659',
    projectId: 'monitoring-650f6',
    storageBucket: 'monitoring-650f6.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy_xiGpp6VEGHRoaLjGlFJdpIFrmOB2qU',
    appId: '1:229806959659:ios:84aa7625adae8fa0d54e6e',
    messagingSenderId: '229806959659',
    projectId: 'monitoring-650f6',
    storageBucket: 'monitoring-650f6.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiMonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtkPDjwxSPfVDsjT4eDKF1wdjxl9EtRoI',
    appId: '1:229806959659:web:c4ec919529131eced54e6e',
    messagingSenderId: '229806959659',
    projectId: 'monitoring-650f6',
    authDomain: 'monitoring-650f6.firebaseapp.com',
    storageBucket: 'monitoring-650f6.firebasestorage.app',
    measurementId: 'G-JPSJMC1ZRX',
  );
}
